version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:2.2.1
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    working_dir: /home/dynamodblocal
    volumes:
      - ./.dynamodb:/home/dynamodblocal/data
    expose:
      - 8000
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    expose:
      - 8001
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_REGION: ap-northeast-1
