// Code generated by go generate; DO NOT EDIT.
package habit

type TypeTemplatePage string

const TemplatePageHabit TypeTemplatePage = "habit.html"
const TemplatePageLogin TypeTemplatePage = "login.html"
const TemplatePageTop TypeTemplatePage = "top.html"
