// Code generated by ifacemaker; DO NOT EDIT.

package api

import (
	"context"

	"github.com/google/uuid"
	"github.com/hareku/habit-tracker-app/internal/auth"
	. "github.com/hareku/habit-tracker-app/internal/repository"
)

type DynamoRepositoryIface interface {
	AllHabits(ctx context.Context, uid auth.UserID) ([]*DynamoHabit, error)
	FindHabit(ctx context.Context, uid auth.UserID, hid uuid.UUID) (*DynamoHabit, error)
	CreateHabit(ctx context.Context, uid auth.UserID, title string) (*DynamoHabit, error)
	DeleteHabit(ctx context.Context, uid auth.UserID, hid uuid.UUID) error
	UpdateHabit(ctx context.Context, in *DynamoRepositoryUpdateHabitInput) error
	ListLatestChecksWithLimit(ctx context.Context, uid auth.UserID, hid uuid.UUID, limit int32) ([]*DynamoCheck, error)
	ListLastWeekChecksInAllHabits(ctx context.Context, uid auth.UserID) ([]*DynamoCheck, error)
	CreateCheck(ctx context.Context, uid auth.UserID, hid uuid.UUID, date string) (*DynamoCheck, error)
	DeleteCheck(ctx context.Context, uid auth.UserID, hid uuid.UUID, date string) error
}
