// Code generated by gen_pages_const; DO NOT EDIT.
package api

type TypeTemplatePage string

const TemplatePageHabit TypeTemplatePage = "habit.html"
const TemplatePageLogin TypeTemplatePage = "login.html"
const TemplatePageTop TypeTemplatePage = "top.html"
